# Generated by Django 4.1 on 2023-07-05 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_text_alter_book_authors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='authors',
        ),
    ]
